use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :webcat, WebCATWeb.Endpoint,
  # Possibly not needed, but doesn't hurt
  http: [port: {:system, "PORT"}],
  url: [host: "flawed-disloyal-invisiblerail.gigalixirapp.com", port: 80],
  secret_key_base: "${SECRET_KEY_BASE}",
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  server: true

config :webcat, WebCATWeb.Auth.Guardian,
  issuer: "webcat",
  secret_key: "${SECRET_KEY_BASE}"

config :webcat, WebCAT.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: "${DATABASE_URL}",
  ssl: true,
  pool_size: 10

config :webcat, WebCAT.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: "smtp.gmail.com",
  # hostname: "",
  port: 587,
  username: "${SMTP_USERNAME}",
  password: "${SMTP_PASWORD}",
  tls: :if_available,
  allowed_tls_versions: [:tlsv1, :"tlsv1.1", :"tlsv1.2"],
  ssl: true,
  retries: 1,
  # can be `true`
  no_mx_lookups: false,
  # can be `always`. If your smtp relay requires authentication set it to `always`.
  auth: :if_available

# Do not print debug messages in production
config :logger, level: :info

config :cors_plug,
  origin: ["*"],
  max_age: 86_400,
  methods: ["GET", "POST", "PATCH", "DELETE"]
