# Generated by Django 3.0.4 on 2020-03-08 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import webcat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcat.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('course_code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='webcat.Category')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('status', models.TextField(choices=[('unreviewed', 'Unreviewed'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved'), ('emailed', 'Emailed')], default='unreviewed')),
                ('notes', models.TextField(blank=True, null=True)),
                ('parent_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcat.Draft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webcat.Draft')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcat.Feedback')),
            ],
            options={
                'unique_together': {('draft', 'feedback')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('number', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcat.Classroom')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcat.Semester')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RotationGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcat.Rotation')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rotation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcat.Section'),
        ),
        migrations.AddField(
            model_name='rotation',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.TextField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcat.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcat.Category')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcat.Draft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcat.Observation'),
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcat.Feedback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='draft',
            name='rotation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcat.RotationGroup'),
        ),
        migrations.AddField(
            model_name='draft',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcat.Draft')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentExplanation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('feedback_id', models.IntegerField()),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webcat.StudentFeedback')),
                ('explanation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcat.Explanation')),
            ],
            options={
                'unique_together': {('draft', 'feedback_id', 'explanation')},
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', webcat.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webcat.Draft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('draft', 'user')},
            },
        ),
    ]
